version: "3.1"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
