version: "3.1"
services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
  postgres:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./app:/app
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
